[package]
name = "genmac"
description = "Generate a valid MAC Adress number."
repository = "https://github.com/Sigmw/mac-generator"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
rand = "0.7"
